dia=input('dia=')
mes=input('mes=')
ano=input('ano')
print('Você nasceu no dia', dia, 'de', mes,'de', ano,'. Correto?')
print('Você nasceu no dia {}'.format(dia),'de {}'.format(mes),'de {}'.format(ano),'. Correto?')
