n1= int(input('Primeiro numero='))
n2= int(input('Segundo numero='))
soma=(n1 + n2)
print('A soma entre {} e {} é igual a {}.'.format(n1,n2,soma))
#print('A raiz quadrada {} é igual a {:.2f}'.format(num,raiz))
